# def test_fail():
#     '''This test causes an assertion error for testing purposes'''
#     assert(False)